#!/usr/bin/env bash
# Script that configures HAproxy in a load balancer.

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen webapp 0.0.0.0:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 6516-web-01 3.235.60.205 check\n\tserver 6516-web-02 44.192.74.250 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
